version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: task_manager
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  flask-app:
    build: .
    container_name: flask_container
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
      MYSQL_DB: task_manager
    depends_on:
      - db
    restart: always

volumes:
  mysql_data:
