version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_todo
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todo_db
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  flask_app:
    build: .
    container_name: flask_todo_app
    restart: always
    depends_on:
      - db
    environment:
      FLASK_ENV: production
      DB_HOST: db
      DB_USER: flaskuser
      DB_PASSWORD: flaskpassword
      DB_NAME: todo_db
    ports:
      - "5000:5000"
    volumes:
      - .:/app

volumes:
  mysql_data:
